### ISSUE TITLE
Is the type Image now ImageMeta?

### ISSUE THREAD

**Issue by einzigsue** [JuliaImages/ImageMetadata.jl#24]
I cannot construct a image with Image(A, prop1=val1, prop2=val2,...) as the document suggested. Can I use a ImageMeta variable same as the way the Image variable was used? 

Cheers
Yue

**Comment by timholy** [comment]
Yes, although some of the properties have become part of the type system. Which document are you looking at? (It must be more than a year old.) The current documentation is at http://juliaimages.github.io/latest/.

You might find it easiest to `Pkg.pin("Images", v"0.10.1")` or so. The reason being that before version 0.11.0, JuliaImages packages gave you tips (deprecation warnings) about how to convert old syntax into new syntax. But the new syntax has been around for so long now that current versions of Images have deleted the tips. Once you get your code working with the new syntax, then you can use `Pkg.free("Images")` to go back to a modern version.

**Comment by timholy** [comment]
You might also need to pin ImageCore (`v0.4.1`), ImageAxes (`v0.3.1`), and ImageMetadata (`v0.3.0`).
